language: node_js

node_js:
  - '20'
  - '18'

cache:
  directories:
    - $HOME/.npm
    - .eslintcache

if: tag IS blank # do not build tags

install:
  - npm ci

script:
  - npm test
  - npm run cover

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: publish
      node_js: '20'
      script: semantic-release
